{% set name = "opentelemetry-instrumentation-pinecone" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 01a827e5d18b5a091489cafa0ca9a6936755850f12cb9a7a6d6d5a9adb3eb0e2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - poetry-core
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
  run_constrained:
    - pinecone >=5.1.0,<9.0.0

# Tests/imports require pinecone, not available in main.
test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Pinecone instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This library allows tracing client-side calls to Pinecone vector DB sent with the official Pinecone library.

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - reachable_url
    - missing_imports_or_run_test_py
